package CarPark;


/**
* CarPark/EntryGateOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Thursday, 4 April 2019 16:06:45 o'clock BST
*/

public interface EntryGateOperations 
{
  CarPark.Machine machine ();
  String machine_name ();
  void registerGate (String machineName);
  void car_entered (String reg);
  void toggleEnabled ();
  void reset ();
} // interface EntryGateOperations
