package CarPark;


/**
* CarPark/ExitGateOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Tuesday, 2 April 2019 02:25:46 o'clock BST
*/

public interface ExitGateOperations 
{
  String machine_name ();
  void registerGate (String machineName);
  void car_exited (String reg);
  void toggleEnabled ();
  void reset ();
} // interface ExitGateOperations
