package CarPark;


/**
* CarPark/ExitGateOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Wednesday, 3 April 2019 19:58:29 o'clock BST
*/

public interface ExitGateOperations 
{
  CarPark.Machine machine ();
  String machine_name ();
  void registerGate (String machineName);
  void car_exited (String reg);
  void toggleEnabled ();
  void reset ();
} // interface ExitGateOperations
