package CarPark;


/**
* CarPark/ExitGate.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ExitGate.idl
* Friday, 8 March 2019 11:06:41 o'clock GMT
*/

public interface ExitGate extends ExitGateOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ExitGate
