package CarPark;

/**
* CarPark/HQServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HQServer.idl
* Friday, 8 March 2019 11:06:51 o'clock GMT
*/

public final class HQServerHolder implements org.omg.CORBA.portable.Streamable
{
  public CarPark.HQServer value = null;

  public HQServerHolder ()
  {
  }

  public HQServerHolder (CarPark.HQServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CarPark.HQServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CarPark.HQServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CarPark.HQServerHelper.type ();
  }

}
