package CarPark;


/**
* CarPark/HQServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Monday, 25 March 2019 15:00:50 o'clock GMT
*/

public interface HQServer extends HQServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HQServer
