package CarPark;


/**
* CarPark/HQServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Sunday, 24 March 2019 20:30:41 o'clock GMT
*/

public interface HQServerOperations 
{
  void raise_alarm (CarPark.VehicleEvent event);
  void register_local_server (CarPark.Machine machine);
  CarPark.Machine[] returnEntryGates ();
} // interface HQServerOperations
