package CarPark;


/**
* CarPark/HQServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HQServer.idl
* Friday, 8 March 2019 11:06:51 o'clock GMT
*/

public interface HQServerOperations 
{
  void raise_alarm (CarPark.VehicleEvent event);
  void register_local_server (String server_name, String server_ior);
} // interface HQServerOperations
