package CarPark;


/**
* CarPark/HQServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Tuesday, 26 March 2019 18:12:28 o'clock GMT
*/

public interface HQServerOperations 
{
  void raise_alarm (CarPark.VehicleEvent event);
  void register_local_server (CarPark.Machine machine);
  CarPark.Machine[] returnEntryGates ();
  CarPark.Machine[] returnPayStations ();
  CarPark.Machine[] returnExitGates ();
  void turn_off_entry_gate ();
} // interface HQServerOperations
