package CarPark;


/**
* CarPark/HQServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Monday, 1 April 2019 02:22:42 o'clock BST
*/

public interface HQServer extends HQServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HQServer
