package CarPark;


/**
* CarPark/HQServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Thursday, 28 March 2019 11:47:05 o'clock GMT
*/

public interface HQServer extends HQServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HQServer
