package CarPark;


/**
* CarPark/List_of_parking_transactionsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Thursday, 4 April 2019 16:06:45 o'clock BST
*/

public final class List_of_parking_transactionsHolder implements org.omg.CORBA.portable.Streamable
{
  public CarPark.ParkingTransaction value[] = null;

  public List_of_parking_transactionsHolder ()
  {
  }

  public List_of_parking_transactionsHolder (CarPark.ParkingTransaction[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CarPark.List_of_parking_transactionsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CarPark.List_of_parking_transactionsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CarPark.List_of_parking_transactionsHelper.type ();
  }

}
