package CarPark;


/**
* CarPark/List_of_machinesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Wednesday, 3 April 2019 19:58:29 o'clock BST
*/

public final class List_of_machinesHolder implements org.omg.CORBA.portable.Streamable
{
  public CarPark.Machine value[] = null;

  public List_of_machinesHolder ()
  {
  }

  public List_of_machinesHolder (CarPark.Machine[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CarPark.List_of_machinesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CarPark.List_of_machinesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CarPark.List_of_machinesHelper.type ();
  }

}
