package CarPark;


/**
* CarPark/Machine.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Friday, 22 March 2019 11:46:23 o'clock GMT
*/

public final class Machine implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String ior = null;

  public Machine ()
  {
  } // ctor

  public Machine (String _name, String _ior)
  {
    name = _name;
    ior = _ior;
  } // ctor

} // class Machine
