package CarPark;


/**
* CarPark/Machine.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Monday, 1 April 2019 02:22:42 o'clock BST
*/

public final class Machine implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String ior = null;
  public boolean enabled = false;

  public Machine ()
  {
  } // ctor

  public Machine (String _name, String _ior, boolean _enabled)
  {
    name = _name;
    ior = _ior;
    enabled = _enabled;
  } // ctor

} // class Machine
