package CarPark;


/**
* CarPark/ParkingTransactionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Monday, 1 April 2019 16:56:03 o'clock BST
*/

abstract public class ParkingTransactionHelper
{
  private static String  _id = "IDL:CarPark/ParkingTransaction:1.0";

  public static void insert (org.omg.CORBA.Any a, CarPark.ParkingTransaction that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CarPark.ParkingTransaction extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = CarPark.TimeHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "entryTime",
            _tcOf_members0,
            null);
          _tcOf_members0 = CarPark.DateHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "entryDate",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "registration_number",
            _tcOf_members0,
            null);
          _tcOf_members0 = CarPark.EventTypeHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "event",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[4] = new org.omg.CORBA.StructMember (
            "hrsStay",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[5] = new org.omg.CORBA.StructMember (
            "amountPaid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "paystationName",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (CarPark.ParkingTransactionHelper.id (), "ParkingTransaction", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CarPark.ParkingTransaction read (org.omg.CORBA.portable.InputStream istream)
  {
    CarPark.ParkingTransaction value = new CarPark.ParkingTransaction ();
    value.entryTime = CarPark.TimeHelper.read (istream);
    value.entryDate = CarPark.DateHelper.read (istream);
    value.registration_number = istream.read_string ();
    value.event = CarPark.EventTypeHelper.read (istream);
    value.hrsStay = istream.read_short ();
    value.amountPaid = istream.read_double ();
    value.paystationName = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CarPark.ParkingTransaction value)
  {
    CarPark.TimeHelper.write (ostream, value.entryTime);
    CarPark.DateHelper.write (ostream, value.entryDate);
    ostream.write_string (value.registration_number);
    CarPark.EventTypeHelper.write (ostream, value.event);
    ostream.write_short (value.hrsStay);
    ostream.write_double (value.amountPaid);
    ostream.write_string (value.paystationName);
  }

}
