package CarPark;

/**
* CarPark/ParkingTransactionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Monday, 1 April 2019 23:20:57 o'clock BST
*/

public final class ParkingTransactionHolder implements org.omg.CORBA.portable.Streamable
{
  public CarPark.ParkingTransaction value = null;

  public ParkingTransactionHolder ()
  {
  }

  public ParkingTransactionHolder (CarPark.ParkingTransaction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CarPark.ParkingTransactionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CarPark.ParkingTransactionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CarPark.ParkingTransactionHelper.type ();
  }

}
