package CarPark;


/**
* CarPark/PayStation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Monday, 11 March 2019 12:23:12 o'clock GMT
*/

public interface PayStation extends PayStationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PayStation
