package CarPark;


/**
* CarPark/PayStationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Wednesday, 3 April 2019 19:58:29 o'clock BST
*/

public interface PayStationOperations 
{
  CarPark.Machine machine ();
  String machine_name ();
  void registerPaystation (String machineName);
  void toggleEnabled ();
  void reset ();
  void pay (String carReg, int duration, double amountPaid);
  double return_cash_total ();
} // interface PayStationOperations
