package CarPark;


/**
* CarPark/PayStationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Tuesday, 2 April 2019 02:25:46 o'clock BST
*/

public interface PayStationOperations 
{
  String machine_name ();
  void registerPaystation (String machineName);
  void toggleEnabled ();
  void reset ();
  void pay (String carReg, int duration, double amountPaid);
  double return_cash_total ();
} // interface PayStationOperations
