package CarPark;


/**
* CarPark/PayStationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Sunday, 24 March 2019 20:30:41 o'clock GMT
*/

public interface PayStationOperations 
{
  String machine_name ();
  void registerPaystation (String machineName, String ior);
  void turn_on ();
  void turn_off ();
  void reset ();
  boolean checkVehicleInCarPark (String carReg);
  boolean createTicket (CarPark.Ticket newTicket);
  boolean pay (String carReg, CarPark.Date payDate, CarPark.Time payTime, int duration);
  int return_cash_total ();
} // interface PayStationOperations
