package CarPark;


/**
* CarPark/Ticket.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Tuesday, 26 March 2019 18:12:28 o'clock GMT
*/

public final class Ticket implements org.omg.CORBA.portable.IDLEntity
{
  public String registration_number = null;
  public double amountPaid = (double)0;
  public CarPark.Date dateEntered = null;
  public CarPark.Time timeEntered = null;
  public CarPark.Date dateToLeave = null;
  public CarPark.Time timeToLeave = null;

  public Ticket ()
  {
  } // ctor

  public Ticket (String _registration_number, double _amountPaid, CarPark.Date _dateEntered, CarPark.Time _timeEntered, CarPark.Date _dateToLeave, CarPark.Time _timeToLeave)
  {
    registration_number = _registration_number;
    amountPaid = _amountPaid;
    dateEntered = _dateEntered;
    timeEntered = _timeEntered;
    dateToLeave = _dateToLeave;
    timeToLeave = _timeToLeave;
  } // ctor

} // class Ticket
