package CarPark;


/**
* CarPark/VehicleEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Monday, 1 April 2019 00:21:05 o'clock BST
*/

public final class VehicleEvent implements org.omg.CORBA.portable.IDLEntity
{
  public CarPark.Time time = null;
  public CarPark.Date date = null;
  public String registration_number = null;
  public CarPark.EventType event = null;
  public short hrsStay = (short)0;
  public double amountPaid = (double)0;
  public String paystationName = null;

  public VehicleEvent ()
  {
  } // ctor

  public VehicleEvent (CarPark.Time _time, CarPark.Date _date, String _registration_number, CarPark.EventType _event, short _hrsStay, double _amountPaid, String _paystationName)
  {
    time = _time;
    date = _date;
    registration_number = _registration_number;
    event = _event;
    hrsStay = _hrsStay;
    amountPaid = _amountPaid;
    paystationName = _paystationName;
  } // ctor

} // class VehicleEvent
