package CarPark;


/**
* CarPark/VehicleEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Sunday, 24 March 2019 20:30:41 o'clock GMT
*/

public final class VehicleEvent implements org.omg.CORBA.portable.IDLEntity
{
  public CarPark.Time time = null;
  public CarPark.Date date = null;
  public String registration_number = null;
  public CarPark.EventType event = null;

  public VehicleEvent ()
  {
  } // ctor

  public VehicleEvent (CarPark.Time _time, CarPark.Date _date, String _registration_number, CarPark.EventType _event)
  {
    time = _time;
    date = _date;
    registration_number = _registration_number;
    event = _event;
  } // ctor

} // class VehicleEvent
