package CarPark.LocalServerPackage;


/**
* CarPark/LocalServerPackage/List_of_entrygatesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Thursday, 21 March 2019 11:21:13 o'clock GMT
*/

public final class List_of_entrygatesHolder implements org.omg.CORBA.portable.Streamable
{
  public CarPark.Ticket value[] = null;

  public List_of_entrygatesHolder ()
  {
  }

  public List_of_entrygatesHolder (CarPark.Ticket[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CarPark.LocalServerPackage.List_of_entrygatesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CarPark.LocalServerPackage.List_of_entrygatesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CarPark.LocalServerPackage.List_of_entrygatesHelper.type ();
  }

}
